### ISSUE TITLE
To recognize non-alphanumeric tokens

### ISSUE THREAD

**Issue by NLKNguyen** [hdima/python-syntax#28]
Hi,
I design this [Paper Color]( http://github.com/NLKNguyen/papercolor-theme) theme, and it supports your syntax plugin. Do you plan to make your plugin to recognize non-alphanumeric tokens like ( ) [ ] , . + - * / = < >  ?

**Comment by hdima** [comment]
Hmm, I don't think so. It seems there's no reason to do that for Python syntax.

I've checked your color scheme and I think you probably shouldn't use syntax groups local to syntax highlighting scripts directly. Local groups can be changed without notice. If you check some other Vim color schemes they all map colors to syntax groups. You can see syntax groups in Vim with `:help group-name` and also `:help highlight-groups`.

**Comment by NLKNguyen** [comment]
I see. I just feel like the local groups in your script enable a lot of design opportunities, and they're just too good to be wasted :).  Actually, this color scheme already defined colors for standard syntax groups (I based on Tomorrow), so it has some predefined colors to fall back in case the script's local groups changed. The fact is when the syntax plugin becomes mature, it's likely to stay mostly the same for years like many other syntax plugins.

Oh and the reason I asked about a group for those symbols is because it can make the syntax look nicer with those symbols more distinguishable, like the operators, parens, and delimiters in this sample script.
![dtrace](https://cloud.githubusercontent.com/assets/4667129/7952226/74f18c2e-0967-11e5-93df-ca54d7e3ecd0.png)

**Comment by hdima** [comment]
In my opinion syntax highlighting for code should help to easily recognize code elements that matters. So I don't think that highlighting for punctuation characters is a good idea in case of Python.
