### ISSUE TITLE
vim's default pyrex.vim requires a pythonInclude group

### ISSUE THREAD

**Issue by anntzer** [hdima/python-syntax#30]
Like it or not, the pyrex syntax file shipped with vim7.4 (extension .pyx) forcefully loads the python syntax file and clears the pythonInclude group, leading to an error with this python syntax file as it does not define pythonInclude anymore.
I would thus suggest providing an empty pythonInclude group to avoid this issue.

**Comment by hdima** [comment]
Can you create a pull request with empty `pythonInclude` group and a comment about `pyrex`?

**Comment by hdima** [comment]
Thank you! I've merged 67b6d85
