### ISSUE TITLE
None is highlighted differently in Python 3 than in Python 2

### ISSUE THREAD

**Issue by gotgenes** [hdima/python-syntax#33]
This plugin's syntax file treats `None` as a [`pythonBuiltinObj` for Python 2](https://github.com/hdima/python-syntax/blob/10d2c07687b611b7c647ad09b8b86ed968819dbd/syntax/python.vim#L398), but as a [`pythonStatement` for Python 3](https://github.com/hdima/python-syntax/blob/10d2c07687b611b7c647ad09b8b86ed968819dbd/syntax/python.vim#L174). This causes different highlighting for `None` in Python 2 versus Python 3, since [`pythonBuiltinObj` maps to the `Structure` group](https://github.com/hdima/python-syntax/blob/10d2c07687b611b7c647ad09b8b86ed968819dbd/syntax/python.vim#L556), but [`pythonStatement` maps to the `Statement` group](https://github.com/hdima/python-syntax/blob/10d2c07687b611b7c647ad09b8b86ed968819dbd/syntax/python.vim#L494).
1. Why did this plugin's maintainers decide the highlighting group for `None` should be different between Python 2 and Python 3? I'm not aware of anything different in the behavior of `None` from Python 2 to Python 3.
2. Doesn't [`None` — a builtin _constant_](https://docs.python.org/3/library/constants.html#None) — most logically map to the `Constant` group, rather than `Structure` or (especially) `Statement`? (The same goes for other builtin constants like `True`, `False`, etc.)

**Comment by hdima** [comment]
The idea is to show differences in implementation of `None`. In Python 2 `None` is a built-in object/type and it was possible to assign to `None` prior to Python 2.4. In Python 3 `None` is a part of the grammar so it can be seen more as a statement. And the same goes for `True` and `False`.

**Comment by nfnty** [comment]
This has been fixed over at the fork [vim-python/python-syntax](https://github.com/vim-python/python-syntax).
