### ISSUE TITLE
No difference in highlighting of `print` between Python 2 and 3

### ISSUE THREAD

**Issue by ukch** [hdima/python-syntax#40]
`print` has changed from a statement to a built-in function between Python 2 and 3. I would expect the syntax highlighting to reflect this change.

**Comment by hdima** [comment]
It does. However if you set `python_print_as_function` option it will highlight `print` as a function for Python 2. And moreover `python_print_as_function` will be set automatically if `python_highlight_all` option is set. So I guess you just need to add `let python_print_as_function = 0` to your configuration.
