### ISSUE TITLE
highliting isn't semantic aware.

### ISSUE THREAD

**Issue by purpleP** [hdima/python-syntax#45]
<img width="281" alt="screenshot 2016-01-07 17 55 50" src="https://cloud.githubusercontent.com/assets/6205841/12173452/efd2fd68-b567-11e5-87ca-da2bf52d3c84.png">
<img width="217" alt="screenshot 2016-01-07 17 55 58" src="https://cloud.githubusercontent.com/assets/6205841/12173453/efff5ae8-b567-11e5-8b69-bb8dba96b1c3.png">
<img width="302" alt="screenshot 2016-01-07 17 56 26" src="https://cloud.githubusercontent.com/assets/6205841/12173465/fe7ecfa4-b567-11e5-980c-85295d3084a4.png">

As you can see from screenshots pycharm nows that len is bultin function and hightlights it, but if I define variable named len for some evil reason (and I sometimes do it with dict) it knows that it's the variable and not the function call, so it doesn't highlight it, unlike your highlighter.

**Comment by hdima** [comment]
Thank you for the report! AFAIK PyCharm parse Python code and uses [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) to represent code internally. So it's possible to do language aware code highlighting, automatic refactoring, type guessing, etc. However syntax highlighting in Vim just uses regex based pattern matching so it's impossible or really expensive to do language aware syntax highlighting. So it won't be fixed unfortunately.

PS. If you really like language aware syntax highlighting in PyCharm I think they also have Vim mode/plugin.
