### ISSUE TITLE
""" or ''' as comments

### ISSUE THREAD

**Issue by nbari** [hdima/python-syntax#7]
how to mark starting and ending strings with """ or ''' as comment

currently as a workaround I added the following to the .vim/after/syntax/python.vim file

syn region Comment start=/"""/ end=/"""/
syn region Comment start=/'''/ end=/'''/

**Comment by jakar** [comment]
This can be done more easily with PR #55. Link `pythonStringMultiline`, `pythonRawStringMultiline`, and so on to the `Comment` group.

Alternatively, you could highlight/link those differently than both strings and comments. I do that to make docstrings stand out.
